// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bankingApp.data;

#nullable disable

namespace bankingApp.Migrations
{
    [DbContext(typeof(BankingDbContext))]
    [Migration("20260924212114_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("bankingApp.data.entities.accounts.BankAccount", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("balance");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("account_type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("AccountId");

                    b.HasIndex("CustomerId");

                    b.ToTable("bank_accounts", (string)null);

                    b.HasDiscriminator<string>("account_type").HasValue("BankAccount");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("bankingApp.data.entities.chequebook.ChequeBookRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<DateTime?>("RequestApprovedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("request_approved_date");

                    b.Property<DateTime>("RequestDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("request_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("RequestStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("request_status");

                    b.HasKey("RequestId");

                    b.HasIndex("AccountId");

                    b.ToTable("cheque_book_requests", (string)null);
                });

            modelBuilder.Entity("bankingApp.data.entities.transactions.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("transaction_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("transaction_direction");

                    b.Property<int?>("RecipientAccountId")
                        .HasColumnType("int")
                        .HasColumnName("recipient_account_id");

                    b.Property<decimal>("TransactionAmount")
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("transaction_amount");

                    b.Property<DateTime>("TransactionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("transaction_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("transaction_type");

                    b.HasKey("TransactionId");

                    b.HasIndex("AccountId");

                    b.HasIndex("RecipientAccountId");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("bankingApp.data.entities.users.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("username");

                    b.Property<string>("user_type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("UserId");

                    b.ToTable("users", (string)null);

                    b.HasDiscriminator<string>("user_type").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("bankingApp.data.entities.accounts.CheckingAccount", b =>
                {
                    b.HasBaseType("bankingApp.data.entities.accounts.BankAccount");

                    b.HasDiscriminator().HasValue("Checking");
                });

            modelBuilder.Entity("bankingApp.data.entities.accounts.LoanAccount", b =>
                {
                    b.HasBaseType("bankingApp.data.entities.accounts.BankAccount");

                    b.Property<decimal?>("OriginalLoanAmount")
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("original_loan_amount");

                    b.HasDiscriminator().HasValue("Loan");
                });

            modelBuilder.Entity("bankingApp.data.entities.accounts.SavingsAccount", b =>
                {
                    b.HasBaseType("bankingApp.data.entities.accounts.BankAccount");

                    b.Property<DateTime?>("PeriodStart")
                        .HasColumnType("datetime2")
                        .HasColumnName("period_start");

                    b.Property<int?>("WithdrawalLimitPerMonth")
                        .HasColumnType("int")
                        .HasColumnName("withdrawal_limit_per_month");

                    b.Property<int?>("WithdrawalsThisPeriod")
                        .HasColumnType("int")
                        .HasColumnName("withdrawals_this_period");

                    b.HasDiscriminator().HasValue("Savings");
                });

            modelBuilder.Entity("bankingApp.data.entities.users.Admin", b =>
                {
                    b.HasBaseType("bankingApp.data.entities.users.User");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("bankingApp.data.entities.users.Customer", b =>
                {
                    b.HasBaseType("bankingApp.data.entities.users.User");

                    b.HasDiscriminator().HasValue("Customer");
                });

            modelBuilder.Entity("bankingApp.data.entities.accounts.BankAccount", b =>
                {
                    b.HasOne("bankingApp.data.entities.users.Customer", "Customer")
                        .WithMany("BankAccounts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("bankingApp.data.entities.chequebook.ChequeBookRequest", b =>
                {
                    b.HasOne("bankingApp.data.entities.accounts.BankAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_cheque_requests_accounts");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("bankingApp.data.entities.transactions.Transaction", b =>
                {
                    b.HasOne("bankingApp.data.entities.accounts.BankAccount", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_transactions_accounts");

                    b.HasOne("bankingApp.data.entities.accounts.BankAccount", "RecipientAccount")
                        .WithMany()
                        .HasForeignKey("RecipientAccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_transactions_recipient");

                    b.Navigation("Account");

                    b.Navigation("RecipientAccount");
                });

            modelBuilder.Entity("bankingApp.data.entities.accounts.BankAccount", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("bankingApp.data.entities.users.Customer", b =>
                {
                    b.Navigation("BankAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
